# Generated by Django 5.0.3 on 2024-05-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_roles_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='roles',
        ),
        migrations.AddField(
            model_name='event',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='event.role'),
        ),
    ]
