# Generated by Django 5.0.3 on 2024-05-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_role_remove_event_roles_event_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='roles',
        ),
        migrations.AddField(
            model_name='event',
            name='roles',
            field=models.TextField(blank=True, null=True, verbose_name='Role'),
        ),
    ]
