# Generated by Django 5.0.3 on 2024-05-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_roles_event_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='event',
            name='roles',
        ),
    ]
